title: Jincheng Wang's Homepage
page-top-title: Jincheng Wang
top-section-bg-text: Computer Science
home-subtitle: Jincheng Wang&ensp;|&ensp;Ash
copyright-text: '&copy; Jincheng Wang 2023-2024. All Rights Reserved.'
